inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

AllCops:
  TargetRubyVersion: 2.7

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
